use std::{io::Error, path::Path};

use rand::Rng;
use tokio::{
    fs::File,
    io::{AsyncReadExt, AsyncWriteExt},
};

/// Read a large file from the given path.
///
/// The file is read in an async manner.
pub async fn read_large_file(path: impl AsRef<Path>) -> Result<Vec<u8>, Error> {
    let mut file = File::open(path).await?;
    let mut buffer = Vec::new();
    file.read_to_end(&mut buffer).await?;
    Ok(buffer)
}

/// Generate a random file with the given size in MB.
///
/// The file is created in the path provided and in an
/// async manner.
pub async fn generate_random_file(path: impl AsRef<Path>, size_mb: usize) -> Result<(), Error> {
    let mut file = File::create(path).await?;
    let mut rng = rand::thread_rng();
    let chunk_size = 1024 * 1024;
    let total_chunks = size_mb;

    for _ in 0..total_chunks {
        let mut chunk = vec![0u8; chunk_size];
        rng.fill(&mut chunk[..]);
        AsyncWriteExt::write_all(&mut file, &chunk).await?;
    }

    Ok(())
}

/// Generate random bytes that can be used to test the file system.
///
/// The generated bytes are not guaranteed to be unique, but it
/// uses a good random number generator.
pub async fn generate_random_bytes(size: usize) -> Result<Vec<u8>, Error> {
    let mut rng = rand::thread_rng();
    let mut bytes = vec![0u8; size];
    rng.fill(&mut bytes[..]);
    Ok(bytes)
}
