name: DockerX Workflow
on:
  push:
    tags:
      - "*"
    branches-ignore:
      - none
  workflow_dispatch:
jobs:
  fast:
    name: Fast (${{ matrix.config.dockerfile }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { dockerfile: "Dockerfile", tag_suffix: "-amd64" }
          - { dockerfile: "Dockerfile.minimal", tag_suffix: "-minimal-amd64" }
    uses: ./.github/workflows/dockerx-build.yml
    with:
      dockerfile: ${{ matrix.config.dockerfile }}
      platforms: "linux/amd64"
      tag_suffix: ${{ matrix.config.tag_suffix }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  full:
    name: Full (${{ matrix.config.dockerfile }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { dockerfile: "Dockerfile", tag_suffix: "", platforms: "linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8" }
          - { dockerfile: "Dockerfile.minimal", tag_suffix: "-minimal", platforms: "linux/amd64,linux/arm64/v8" }
    uses: ./.github/workflows/dockerx-build.yml
    with:
      dockerfile: ${{ matrix.config.dockerfile }}
      platforms: ${{ matrix.config.platforms }}
      tag_suffix: ${{ matrix.config.tag_suffix }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
